[tool.poetry]
name = "my-project"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
anyio = "3.6.2"
asgiref = "3.6.0"
blinker = "1.6.2"
certifi = "2022.12.7"
chardet = "5.1.0"
charset-normalizer = "3.1.0"
click = "8.1.3"
colorama = "0.4.6"
contourpy = "1.0.7"
cryptography = "38.0.4"
cycler = "0.11.0"
dbus-python = "1.3.2"
distro = "1.8.0"
dnspython = "2.3.0"
fastapi = "0.95.0"
Flask = "2.3.1"
fonttools = "4.39.3"
gyp = "0.1"
h11 = "0.14.0"
httplib2 = "0.20.4"
idna = "3.4"
itsdangerous = "2.1.2"
Jinja2 = "3.1.2"
joblib = "1.2.0"
jsonpickle = "3.0.1"
kiwisolver = "1.4.4"
lazr.restfulclient = "0.14.5"
lazr.uri = "1.0.6"
MarkupSafe = "2.1.2"
matplotlib = "3.7.1"
more-itertools = "9.1.0"
music21 = "8.1.0"
numpy = "1.24.3"
oauthlib = "3.2.2"
opencv-python = "4.5.5.62"
packaging = "23.1"
Pillow = "9.5.0"
pydantic = "1.10.7"
PyGObject = "3.42.2"
PyJWT = "2.6.0"
pymongo = "4.3.3"
pyparsing = "3.0.9"
python-apt = "2.5.3"
python-dateutil = "2.8.2"
python-multipart = "0.0.6"
requests = "2.28.2"
six = "1.16.0"
sniffio = "1.3.0"
starlette = "0.26.1"
typing-extensions = "4.5.0"
urllib3 = "1.26.15"
uvicorn = "0.21.1"
wadllib = "1.3.6"
webcolors = "1.13"
Werkzeug = "2.3.0"
wsproto = "1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

